/**
 * AdBoard API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ShortCategoryDto } from './short-category-dto';


/**
 * Данные о категории
 */
export interface CategoryDto { 
    /**
     * Id.
     */
    id?: string;
    /**
     * Название.
     */
    name?: string | null;
    /**
     * Id категории выше по иерархии.
     */
    parentId?: string;
    /**
     * Дочерние категории
     */
    childs?: Array<ShortCategoryDto> | null;
}

