/**
 * AdBoard API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ShortUserDto } from './short-user-dto';
import { ShortAdvertDto } from './short-advert-dto';


/**
 * Информация о комментарии
 */
export interface CommentDto { 
    /**
     * Идентификатор
     */
    id?: string | null;
    /**
     * Содержимое комментария
     */
    text?: string | null;
    /**
     * Дата создания
     */
    created?: string;
    /**
     * Родитель (если комментарий является ответом на другой комментарий)
     */
    parentId?: string | null;
    advert?: ShortAdvertDto;
    user?: ShortUserDto;
}

