/**
 * AdBoard API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Данные для создания нового пользователя
 */
export interface CreateUserDto { 
    /**
     * Имя пользователя
     */
    name: string;
    /**
     * Логин
     */
    login: string;
    /**
     * Пароль
     */
    password: string;
}

