/**
 * AdBoard API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Модель ошибки.
 */
export interface ErrorDto { 
    /**
     * Код ошибки.
     */
    errorCode?: string | null;
    /**
     * Сообщение для пользователя.
     */
    userMessage?: string | null;
    /**
     * Вложенные ошибки.
     */
    internalErrors?: Array<ErrorDto> | null;
}

