/**
 * AdBoard API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Модель категории для импорта из JSON.
 */
export interface ImportCategoryDto { 
    /**
     * Идентификатор категории.
     */
    id?: number;
    /**
     * Наименование категории.
     */
    name?: string | null;
    /**
     * Идентификатор родительской категории.
     */
    parentId?: number | null;
}

