/**
 * AdBoard API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ShortUserDto } from './short-user-dto';


/**
 * Сокращенная информация о комментарии
 */
export interface ShortCommentDto { 
    /**
     * Идентификатор
     */
    id?: string | null;
    /**
     * Содержимое комментария
     */
    text?: string | null;
    /**
     * Дата создания
     */
    created?: string;
    /**
     * Идентификатор родительского комментария
     */
    parentId?: string | null;
    user?: ShortUserDto;
}

