/**
 * AdBoard API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Краткая информация об объявлении
 */
export interface ShortAdvertDto { 
    /**
     * Идентификатор
     */
    id?: string;
    /**
     * Название
     */
    name?: string | null;
    /**
     * Геолокация объявления
     */
    location?: string | null;
    /**
     * Дата создания.
     */
    createdAt?: string;
    /**
     * Признак актуальности объявления.
     */
    isActive?: boolean;
    /**
     * Изображения
     */
    imagesIds?: Array<string> | null;
    /**
     * Цена
     */
    cost?: number;
}

