/**
 * AdBoard API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Краткое описание категории
 */
export interface ShortCategoryDto { 
    /**
     * Идентификатор
     */
    id?: string;
    /**
     * Родительская категория
     */
    parentId?: string;
    /**
     * Название
     */
    name?: string | null;
}

