/**
 * AdBoard API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ShortAdvertDto } from './short-advert-dto';


/**
 * Полная информация о пользователе
 */
export interface UserDto { 
    /**
     * Идентификатор
     */
    id?: string;
    /**
     * Имя пользователя
     */
    name?: string | null;
    /**
     * Роль
     */
    role?: string | null;
    /**
     * Объявления
     */
    adverts?: Array<ShortAdvertDto> | null;
    /**
     * Дата регистрации
     */
    registeredTime?: string;
}

