export * from './advert.service';
import { AdvertService } from './advert.service';
export * from './advert.serviceInterface';
export * from './authorization.service';
import { AuthorizationService } from './authorization.service';
export * from './authorization.serviceInterface';
export * from './categories.service';
import { CategoriesService } from './categories.service';
export * from './categories.serviceInterface';
export * from './comment.service';
import { CommentService } from './comment.service';
export * from './comment.serviceInterface';
export * from './images.service';
import { ImagesService } from './images.service';
export * from './images.serviceInterface';
export * from './users.service';
import { UsersService } from './users.service';
export * from './users.serviceInterface';
export const APIS = [AdvertService, AuthorizationService, CategoriesService, CommentService, ImagesService, UsersService];
