/**
 * AdBoard API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { CreateUserDto } from '../model/models';
import { ErrorDto } from '../model/models';
import { LoginUserDto } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface AuthorizationServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Аутентифицирует пользователя
     * 
     * @param loginUserDto Модель для аутентификации
     */
    authLoginPost(loginUserDto?: LoginUserDto, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Создаёт пользователя
     * 
     * @param createUserDto Модель пользователя
     */
    authRegisterPost(createUserDto?: CreateUserDto, extraHttpRequestParams?: any): Observable<{}>;

}
