/**
 * AdBoard API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { CommentDto } from '../model/models';
import { ErrorDto } from '../model/models';
import { ShortCommentDto } from '../model/models';
import { UpdateCommentDto } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface CommentServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Удаляет комментарий по ID
     * 
     * @param id Идентификатор
     */
    commentIdDelete(id: string, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Получить комментарий по id
     * 
     * @param id Идентификатор
     */
    commentIdGet(id: string, extraHttpRequestParams?: any): Observable<CommentDto>;

    /**
     * Обновляет комментарий по модели
     * 
     * @param id Идентификатор комментария
     * @param updateCommentDto Модель
     */
    commentIdPut(id: string, updateCommentDto?: UpdateCommentDto, extraHttpRequestParams?: any): Observable<ShortCommentDto>;

}
