/**
 * AdBoard API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ErrorDto } from '../model/models';
import { ShortImageDto } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface ImagesServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Удаляет изображение по ID
     * 
     * @param id Идентификатор изображения
     */
    imagesIdDelete(id: string, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Получить изображение по id
     * 
     * @param id Идентификатор изображения
     */
    imagesIdGet(id: string, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Создаёт изображение по модели
     * 
     * @param advertId Идентификатор объявления
     * @param content Массив байтов, содержащий изображение
     */
    imagesPost(advertId: string, content: Blob, extraHttpRequestParams?: any): Observable<ShortImageDto>;

}
