/**
 * AdBoard API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ErrorDto } from '../model/models';
import { ShortUserDto } from '../model/models';
import { UserDto } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface UsersServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Получить текущего пользователя
     * 
     */
    usersCurrentGet(extraHttpRequestParams?: any): Observable<ErrorDto>;

    /**
     * Вернуть всех пользователей
     * 
     */
    usersGet(extraHttpRequestParams?: any): Observable<Array<ShortUserDto>>;

    /**
     * Удаляет пользователя по ID
     * 
     * @param id Идентификатор пользователя
     */
    usersIdDelete(id: string, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Получить пользователя по id
     * 
     * @param id Идентификатор пользователя
     */
    usersIdGet(id: string, extraHttpRequestParams?: any): Observable<UserDto>;

    /**
     * Обновляет пользователя по модели
     * 
     * @param id Идентификатор обновляемого пользователя
     * @param name Имя пользователя
     * @param login Логин
     * @param password Пароль
     */
    usersIdPut(id: string, name: string, login: string, password: string, extraHttpRequestParams?: any): Observable<ShortUserDto>;

}
